### ISSUE TITLE
设备注册和查到的疑问

### ISSUE THREAD

**Issue by ShineRoyal** [willianchanlovegithub/ds18b20#3]
在ds18b20/sample/ds18b20_sample.c中line 92~93，注册设备时设备名是ds18b20：
    cfg.intf.user_data = (void *)DS18B20_DATA_PIN;
    rt_hw_ds18b20_init("ds18b20", &cfg);
line 25 处rt_device_find的设备名为什么是temp_ds18b20呢

**Comment by willianchanlovegithub** [comment]
sensor框架会在注册传感器设备的时候给传感器的名字前加上传感器类型前缀。
